### ISSUE TITLE
Ensure conda projects use inclusive language

### ISSUE THREAD

**Issue by travishathaway** [conda/infra#557]
### Summary

In order to make everyone in our community feel welcome, we want to remove the use a problematic phrases or terms from our repositories. This includes everything from branch names such as "master" to variable names such as "whitelist"/"blacklist". The issues listed here all contribute to this goal.

### Linked Issues & PRs

- [x] https://github.com/conda/conda/issues/11517
- [x] https://github.com/conda/conda-build/issues/4494
- [x] https://github.com/conda/conda-build/issues/4514
- [x] [conda/schemas](https://github.com/conda/schemas)
- [x] [conda/cookiecutter-conda-python](https://github.com/conda/cookiecutter-conda-python)
- [x] [conda/conda-prefix-replacement](https://github.com/conda/conda-prefix-replacement)
- [x] [conda/conda-benchmarks](https://github.com/conda/conda-benchmarks)
- [x] [conda/conda_build_test_recipe](https://github.com/conda/conda_build_test_recipe)
- [x] [conda/conda_build_single_folder_test](https://github.com/conda/conda_build_single_folder_test)
- [x] [conda/pycosat](https://github.com/conda/pycosat)
- [x] [conda/menuinst](https://github.com/conda/menuinst)
- [x] https://github.com/conda/constructor/pull/528
- [x] https://github.com/conda/conda-verify/pull/84
- [x] [conda/conda-package-handling](https://github.com/conda/conda-package-handling)
- [x] https://github.com/conda/conda-pack/pull/232
- [x] https://github.com/conda/conda-package-handling/pull/118
- [x] https://github.com/conda/infra/pull/584
