### ISSUE TITLE
Store the `.clabot` here in the conda/infra repo

### ISSUE THREAD

**Issue by jezdez** [conda/infra#564]
- [x] Move changes from clabot-config repo into infra repo, retaining the git history (https://github.com/conda/infra/pull/565)
- [x] Update the GHA workflow to use new location, do release (https://github.com/conda/actions/pull/42)
- [ ] Merge all PRs against the various repos to have new GHA workflow in use (TBD)
- [ ] Update README with note in clabot-config (https://github.com/conda/clabot-config/pull/5)
- [ ] Archive the clabot-config repo in https://github.com/conda-archive (TBD)
