### ISSUE TITLE
Update CODE_OF_CONDUCT.md to link to new conda CoC

### ISSUE THREAD

**Issue by kathatherine** [conda/infra#620]
### What is the idea?

Now that the conda org has an official [Code of Conduct](https://github.com/conda-incubator/governance/blob/main/CODE_OF_CONDUCT.md), the [CODE_OF_CONDUCT.md](https://github.com/conda/infra/blob/6f8fb087337dbdf62abcab33267bd20415ad10a4/CODE_OF_CONDUCT.md) file should now link to that instead of NumFOCUS's CoC.

### Tasks

- [ ] ~Update local [`CODE_OF_CONDUCT.md`](https://github.com/conda/infra/blob/main/CODE_OF_CONDUCT.md) to link to conda's governance [`CODE_OF_CONDUCT.md`](https://github.com/conda-incubator/governance/blob/main/CODE_OF_CONDUCT.md)~
- [x] Sync updated `CODE_OF_CONDUCT.md` to all conda repos
- [ ] ~Remove all synced `CODE_OF_CONDUCT.md` from conda org repos~
- [ ] ~Add new CODE_OF_CONDUCT.md to https://github.com/conda/.github~
    - https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types

**Comment by kathatherine** [comment]
@jezdez Works for me. So I just need to replace the content of the CODE_OF_CONDUCT.md in conda/infra and the sync will do the rest? I also have a commit to do the same in conda/.github.

**Comment by kenodegard** [comment]
@kathatherine update CODE_OF_CONDUCT.md in conda/infra, move the CODE_OF_CONDUCT.md in the syncing config into a new group and sync it to all repos + conda/.github

no manual changes to conda/.github needed
